version: '2'
services:
  redis-cluster:
    image: mq/redis-cluster
    container_name: mq-redis-cluster
    network_mode: host
    ports:
    - "7000:7000"
    build:
      context: .
      dockerfile: Dockerfile
