version: '2'
services:
  redis-cluster:
    image: mq/redis-cluster
    container_name: mq-redis-cluster
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7000-7002:7000-7002'
